export const DEV_TYPES = [
	"backend",
	"frontend",
	"fullstack",
	"data-science",
	"dev-ops",
	"blockchain",
	"machine-learning",
	"systems-programming",
	"game-development",
	"security",
];

export const JARGON_LEVELS = ["low", "medium", "high", "extreme"];
export const COMPLEXITIES = ["low", "medium", "high", "extreme"];
export const OUTPUT_FORMATS = ["text", "json"];
export const EXPERIMENTAL_PROVIDERS = [
	"openai-compatible",
	"anthropic",
	"openai-consumer",
	"claude-consumer",
];
export const EXPERIMENTAL_ADAPTER_MODES = ["api", "consumer"];

export const CLI_FLAGS = [
	"alerts",
	"project",
	"minimal",
	"team",
	"framework",
	"seed",
	"output-format",
	"no-color",
	"trace",
	"list-values",
	"experimental-provider",
	"experimental-model",
	"experimental-profile",
	"experimental-prompt",
	"experimental-adapter-mode",
];

const family = (id, title, protocol, group, low, high, extreme) => ({
	id,
	title,
	protocol,
	group,
	messages: { low, medium: low, high, extreme },
});

export const GENERATOR_FAMILIES = [
	family(
		"code-analyzer",
		"Code analyzer",
		null,
		"classic-six",
		"reviewing typed interfaces and SDK drift across the active service graph",
		"triaging monorepo dependency edges, generated patches, and schema compatibility before merge",
		"replaying agent-authored patchsets against contract drift, ownership boundaries, and MCP tool assumptions",
	),
	family(
		"data-processing",
		"Data processing",
		null,
		"classic-six",
		"refreshing embedding corpora, batch transforms, and event windows for the current dataset",
		"rebuilding hybrid retrieval indexes, semantic chunks, and NDJSON backfills for downstream consumers",
		"reconciling multimodal pipelines, lakehouse batch cuts, and evaluation-ready data slices under deterministic ordering",
	),
	family(
		"jargon",
		"Jargon refresh",
		null,
		"classic-six",
		"keeping technical language current without drifting into fake-deep jargon",
		"switching phrasing toward credible 2026 agent, platform, protocol, and security terminology",
		"enforcing modern domain vocabulary so advanced output stays precise instead of sounding synthetic",
	),
	family(
		"metrics",
		"Metrics",
		null,
		"classic-six",
		"tracking queue depth, latency bands, and cost signals across the active workload",
		"correlating token spend, SLO burn, GPU occupancy, and attestation coverage in one metrics lane",
		"folding evaluation score movement, blob economics, and runner pressure into a single operations dashboard",
	),
	family(
		"network-activity",
		"Network activity",
		"grpc",
		"classic-six",
		"observing RPC, event-stream, and adapter traffic across the current service boundary",
		"mapping MCP calls, inference APIs, registry fetches, and cross-domain message flow under backpressure",
		"profiling mixed gRPC, Kafka, MQTT, and bridge traffic while preserving replay semantics and retry windows",
	),
	family(
		"system-monitoring",
		"System monitoring",
		null,
		"classic-six",
		"watching collector pressure, runner health, and process saturation on the active stack",
		"capturing GPU memory pressure, secret-scan spikes, sandbox failures, and scheduler queue churn",
		"stitching host telemetry, proof queues, provisioning lag, and policy denials into one operational heartbeat",
	),
	family(
		"agent-workflows",
		"Agent workflows",
		"mcp",
		"modern-core",
		"routing coding-agent work through review queues and approval gates",
		"coordinating delegated patch runs, blocked tool calls, and human checkpoints across multiple repos",
		"orchestrating branch handoff envelopes, MCP leases, and merge-safe approval chains for background agents",
	),
	family(
		"ai-inference-ops",
		"AI inference ops",
		"responses-api",
		"ai-governance",
		"monitoring model routing, cache hits, and prompt rollouts for live inference paths",
		"tuning fallback chains, context-budget pressure, and eval regressions across provider tiers",
		"balancing retrieval freshness, safety fallbacks, and token-cost envelopes under multi-model orchestration",
	),
	family(
		"platform-engineering",
		"Platform engineering",
		null,
		"modern-core",
		"maintaining golden paths, service templates, and workload identity for self-service delivery",
		"resolving platform policy denials, tenant quotas, and template drift inside the internal developer portal",
		"reconciling workload identity, cluster tenancy, policy bundles, and queue fairness across platform control planes",
	),
	family(
		"supply-chain-security",
		"Supply-chain security",
		null,
		"modern-core",
		"checking artifact trust, secret exposure, and dependency health before release",
		"verifying provenance attestations, AIBOM coverage, revocation posture, and tamper signals across build lanes",
		"gating release promotion on signed artifacts, dependency substitution checks, and cross-tool trust evidence",
	),
	family(
		"observability-ai-runtime",
		"Observability AI runtime",
		null,
		"modern-core",
		"recording traces, token spend, and latency bands for the active runtime",
		"tracking OTel collector saturation, span cardinality, and GPU telemetry alongside tool-call traces",
		"driving burn-rate analysis across inference queues, cost attribution, and distributed reasoning spans",
	),
	family(
		"delivery-preview-ops",
		"Delivery preview ops",
		null,
		"modern-core",
		"managing preview environments, feature flags, and canary promotions for current changes",
		"holding rollout gates on runner saturation, preview drift, and canary health regression signals",
		"sequencing flag freezes, rollback windows, and staged promotion rules across agent-authored delivery pipelines",
	),
	family(
		"evaluation-and-guardrails",
		"Evaluation and guardrails",
		"responses-api",
		"ai-governance",
		"running evaluation suites and schema checks against generated outputs",
		"measuring tool-use regressions, rubric drift, and structured-output failures before release",
		"enforcing guardrail coverage against jailbreak attempts, policy escapes, and benchmark regressions in one pass",
	),
	family(
		"knowledge-retrieval",
		"Knowledge retrieval",
		"responses-api",
		"ai-governance",
		"refreshing vector search indexes and citation coverage for current knowledge sets",
		"repairing stale embeddings, reranker drift, and low-confidence retrieval before answers ship",
		"rebalancing hybrid search, chunk overlap, and provenance coverage under corpus freshness pressure",
	),
	family(
		"edge-client-runtime",
		"Edge client runtime",
		"webtransport",
		"health-protocol",
		"stabilizing edge execution, streaming UI, and offline sync paths",
		"handling hydration boundaries, wasm loads, and client cache invalidation across distributed edges",
		"coordinating edge cold-start budgets, sync conflict recovery, and realtime streaming under browser constraints",
	),
	family(
		"identity-and-trust",
		"Identity and trust",
		null,
		"security-blockchain",
		"maintaining signer trust, workload identity, and delegated access boundaries",
		"rotating keys, validating session trust, and reconciling workload provenance across service edges",
		"stitching smart-account recovery, signer provenance, and delegated authority windows into one trust fabric",
	),
	family(
		"aibom-provenance",
		"AIBOM provenance",
		null,
		"ai-governance",
		"capturing model lineage and runtime dependency provenance for generated outputs",
		"versioning prompt assets, adapter state, and AIBOM evidence with reproducible cache metadata",
		"reconstructing full generation provenance across model lineage, adapter drift, and environment evidence",
	),
	family(
		"agent-boundary-security",
		"Agent boundary security",
		"mcp",
		"security-blockchain",
		"checking unsafe delegation, tool overreach, and principal confusion in agent flows",
		"blocking retrieval poisoning, denial-of-wallet patterns, and cross-boundary action mistakes",
		"hardening planning loops against wrong-principal execution, policy bypass, and agent-to-agent trust collapse",
	),
	family(
		"embedded-agentic-pipeline",
		"Embedded agentic pipeline",
		null,
		"health-protocol",
		"keeping deterministic control loops and constrained inference pipelines stable",
		"coordinating firmware toolchains, on-device models, and traceable agent steps under resource limits",
		"balancing safety-critical timing, agentic orchestration, and hardware build provenance across embedded fleets",
	),
	family(
		"data-governance-compliance",
		"Data governance compliance",
		null,
		"ai-governance",
		"applying retention, consent, and regional handling rules to active data flows",
		"enforcing governed retrieval, explainability evidence, and audit-ready policy checkpoints",
		"reconciling cross-border data use, consent state, and explainability artifacts across automated workflows",
	),
	family(
		"finops-capacity",
		"FinOps capacity",
		null,
		"ai-governance",
		"tracking spend, queue pressure, and storage growth across the active platform",
		"tuning GPU scheduling, preview-environment budgets, and token-cost ceilings against workload demand",
		"balancing inference burn, runner economics, and blob-or-data-availability spend under shared capacity limits",
	),
	family(
		"blockchain-protocol-ops",
		"Blockchain protocol ops",
		null,
		"security-blockchain",
		"processing rollup, validator, and smart-account operations against the current chain state",
		"coordinating gas sponsorship, bridge verification, and sequencer health across modern execution layers",
		"managing rollup batch flow, validator signals, and smart-account recovery under chain-abstraction demands",
	),
	family(
		"cross-chain-interop",
		"Cross-chain interop",
		null,
		"security-blockchain",
		"routing assets and calls across chain boundaries with explicit trust assumptions",
		"coordinating wallet-level chain abstraction, liquidity paths, and cross-domain execution guarantees",
		"sequencing sign-once cross-chain flows with interoperability proofs, settlement safeguards, and bridge-minimized UX",
	),
	family(
		"proof-and-sequencer-ops",
		"Proof and sequencer ops",
		null,
		"security-blockchain",
		"watching proof jobs, sequencing order, and batch submission latency",
		"triaging prover queues, ordering policy, MEV pressure, and data-availability throughput",
		"balancing shared sequencing, proof lag, and finality windows across rollup infrastructure",
	),
	family(
		"hybrid-runtime-ops",
		"Hybrid runtime ops",
		null,
		"overlay-quantum",
		"moving jobs between notebooks, sessions, and managed runtime batches",
		"coordinating hybrid execution windows, session reuse, and cancel-or-retry flow on quantum runtimes",
		"balancing job orchestration across managed sessions, classical sidecars, and backend-specific runtime constraints",
	),
	family(
		"capacity-cost-controller",
		"Capacity and cost controller",
		null,
		"overlay-quantum",
		"tracking queue visibility, reservations, and spend controls on quantum backends",
		"planning reservations, task admission, and budget alerts against scarce quantum capacity",
		"holding hybrid workloads inside reservation windows, spend ceilings, and backend admission constraints",
	),
	family(
		"batch-execution-tuner",
		"Batch execution tuner",
		null,
		"overlay-quantum",
		"assembling parameter sweeps and batched runs for repeatable throughput checks",
		"optimizing batch submission order, parametric compilation reuse, and aggregated result handling",
		"driving high-volume sweep orchestration across batch windows, compilation reuse, and deterministic result collation",
	),
	family(
		"compiler-maintainer",
		"Compiler maintainer",
		"openqasm3",
		"overlay-quantum",
		"adjusting transpiler passes and backend targets for the active circuit set",
		"managing compiler plugins, routing passes, and backend-target mismatch under current constraints",
		"tuning custom transpiler stacks, plugin manifests, and pass-manager behavior across backend generations",
	),
	family(
		"interop-adapter-engineer",
		"Interop adapter engineer",
		"qir",
		"overlay-quantum",
		"translating execution artifacts across QIR, OpenQASM, and adapter boundaries",
		"running round-trip tests between quantum IRs while preserving semantics and backend capability tags",
		"reconciling QIR adaptor output, OpenQASM transforms, and backend profile gaps under interop pressure",
	),
	family(
		"preflight-capacity-planner",
		"Preflight capacity planner",
		null,
		"overlay-quantum",
		"estimating runtime size, qubit demand, and target fit before dispatch",
		"checking backend profiles, resource estimators, and admission limits before quantum submission",
		"gating workloads on qubit budgets, error tolerance, and backend profile constraints before execution",
	),
	family(
		"simulator-performance-engineer",
		"Simulator performance engineer",
		"openqasm3",
		"overlay-quantum",
		"profiling simulator throughput and local-mode performance under current inputs",
		"tuning GPU-backed simulators, container runtime compatibility, and local execution benchmarks",
		"balancing CUDA-class simulation paths, local-mode orchestration, and benchmark repeatability across quantum stacks",
	),
	family(
		"fhir-profile-generator",
		"FHIR profile generator",
		"fhir-r4",
		"health-protocol",
		"generating FHIR R4 resources and profile-constrained clinical records",
		"assembling US Core aligned resource graphs, validation rules, and vendor-capability expectations",
		"producing profile-aware clinical bundles with deployable R4 semantics and forward-looking R5 awareness",
	),
	family(
		"smart-launch-oauth",
		"SMART launch OAuth",
		"smart-launch",
		"health-protocol",
		"negotiating SMART launch context, scopes, and token refresh for current EHR sessions",
		"stabilizing standalone and EHR launch flows with patient, user, and encounter context propagation",
		"coordinating SMART launch scope negotiation, refresh policy, and context handoff across vendor sandboxes",
	),
	family(
		"bulk-fhir-population-ops",
		"Bulk FHIR population ops",
		"bulk-fhir",
		"health-protocol",
		"preparing Bulk FHIR exports and NDJSON population slices",
		"running cohort-scale export jobs, manifest tracking, and downstream analytics handoff for current datasets",
		"coordinating high-volume Bulk Data exports, job polling, and reconciliation against multi-tenant analytics lanes",
	),
	family(
		"hl7v2-feed-ops",
		"HL7 v2 feed ops",
		"hl7v2",
		"health-protocol",
		"processing HL7 v2 feeds, ACKs, and interface-engine traffic for operational workflows",
		"mapping ADT, ORM, ORU, and SIU message behavior into modern validation and bridge checks",
		"reconciling repeating-segment churn, ACK/NACK behavior, and v2-to-FHIR boundary conditions at scale",
	),
	family(
		"clinical-workflow-events",
		"Clinical workflow events",
		"fhir-r4",
		"health-protocol",
		"driving CDS Hooks, subscriptions, and workflow triggers for clinical events",
		"coordinating prior-auth, questionnaire, measure, and case-reporting workflows across FHIR operations",
		"orchestrating subscription events, CDS cards, and payer-provider workflow state under live clinical policy",
	),
	family(
		"dicomweb-imaging-ops",
		"DICOMweb imaging ops",
		"dicomweb",
		"health-protocol",
		"serving imaging studies over QIDO-RS, WADO-RS, and STOW-RS surfaces",
		"matching DICOMweb retrieval, storage, and conformance expectations across modality and PACS flows",
		"balancing DICOMweb ingest, retrieval, and conformance evidence across imaging workflows and archive tiers",
	),
	family(
		"openehr-semantic-record-ops",
		"openEHR semantic record ops",
		"openehr",
		"health-protocol",
		"managing openEHR compositions, templates, and semantic record queries",
		"running archetype-driven data capture with AQL query validation and template-aware persistence",
		"reconciling template semantics, composition versioning, and AQL-driven access across longitudinal records",
	),
	family(
		"device-telemetry-clinical",
		"Device telemetry clinical",
		"ihe-device",
		"health-protocol",
		"tracking bedside device telemetry, alerts, and identity across care settings",
		"coordinating IHE device flows, monitor alarms, and point-of-care telemetry under clinical constraints",
		"balancing device identity, telemetry burst control, and alert escalation across monitored clinical infrastructure",
	),
	family(
		"emr-vendor-adapter",
		"EMR vendor adapter",
		"epic-fhir",
		"health-protocol",
		"aligning application flows with Epic and Oracle Health integration patterns",
		"normalizing vendor-specific launch, scope, and error behavior across EHR adapter boundaries",
		"reconciling vendor capability gaps, sandbox behavior, and operational error modes across EMR integrations",
	),
	family(
		"ocpp-chargepoint-ops",
		"OCPP chargepoint ops",
		"ocpp-2.x",
		"health-protocol",
		"handling charger sessions, heartbeats, and smart-charging commands over OCPP",
		"coordinating OCPP 2.x profiles, security state, and brownfield 1.6 compatibility boundaries",
		"balancing certificate flows, smart charging, and transaction lifecycle state across mixed charger fleets",
	),
	family(
		"ocpi-roaming-ops",
		"OCPI roaming ops",
		"ocpi-2.x",
		"health-protocol",
		"processing roaming session state, tariffs, and settlement exchanges over OCPI",
		"managing CPO-to-EMSP synchronization, booking flow, and roaming settlement at protocol boundaries",
		"reconciling roaming authorization, tariff exchange, and multi-party settlement across current OCPI networks",
	),
	family(
		"mcp-a2a-ops",
		"MCP and A2A ops",
		"mcp",
		"health-protocol",
		"routing tool calls and agent messages across MCP and A2A surfaces",
		"aligning MCP auth, remote tool execution, and AgentCard discovery across agent networks",
		"coordinating MCP resource exchange and A2A task handoff with explicit auth boundaries and policy controls",
	),
	family(
		"streaming-bus-ops",
		"Streaming bus ops",
		"kafka",
		"health-protocol",
		"moving events through MQTT, NATS, and Kafka channels with replay-safe routing",
		"balancing consumer lag, retention, and JetStream-or-Kafka durability across streaming workloads",
		"coordinating brokered telemetry, replay windows, and stream processor contracts across multi-bus topologies",
	),
	family(
		"service-mesh-rpc-ops",
		"Service mesh RPC ops",
		"grpc",
		"health-protocol",
		"serving typed RPC and federated API traffic across internal service boundaries",
		"tuning gRPC, GraphQL federation, and timeout budgets across routed service meshes",
		"reconciling streaming RPC, schema composition, and retry propagation across mesh-aware service fabrics",
	),
];

export const FAMILY_MAP = new Map(GENERATOR_FAMILIES.map((entry) => [entry.id, entry]));

export const CLASSIC_FAMILIES = [
	"code-analyzer",
	"data-processing",
	"metrics",
	"network-activity",
	"system-monitoring",
];

export const POLICY_FAMILIES = [
	"supply-chain-security",
	"observability-ai-runtime",
	"evaluation-and-guardrails",
	"identity-and-trust",
	"aibom-provenance",
	"agent-boundary-security",
	"data-governance-compliance",
	"finops-capacity",
];

export const ALERT_FAMILIES = [
	"supply-chain-security",
	"observability-ai-runtime",
	"agent-boundary-security",
	"device-telemetry-clinical",
	"ocpp-chargepoint-ops",
	"streaming-bus-ops",
	"service-mesh-rpc-ops",
	"mcp-a2a-ops",
];

export const TEAM_FAMILIES = [
	"agent-workflows",
	"platform-engineering",
	"delivery-preview-ops",
	"service-mesh-rpc-ops",
];
